In [1]:
import numpy as np

# Jacobi

In [2]:
M = np.array([[3,-1,-1],[-1.,3.,1.],[2,1,4]])
print(M)
b = np.array([1.,3.,7.])
print(b)

[[ 3. -1. -1.]
 [-1.  3.  1.]
 [ 2.  1.  4.]]
[1. 3. 7.]


In [3]:
np.linalg.solve(M,b)

array([1., 1., 1.])

In [8]:
def GetacobiMethod(A,b,itmax=1000,error = 1e-10):
    
    M,N = A.shape
    
    x = np.zeros(N)
    
    sumk = np.zeros_like(x)
    
    x = [13,20,-1]
    
    it = 0
    
    residuo = np.linalg.norm( b - np.dot(A,x) )
    
    while ( residuo > error and it < itmax ):
        
        it += 1
        
        for i in range(M):
            sum_ = 0
            for j in range(N):
                if i != j:
                    sum_ += A[i][j]*x[j]
            sumk[i] = sum_
          
        for i in range(M):
            
            if A[i,i] != 0:
                x[i] = (b[i] - sumk[i])/A[i,i]
            else:
                print('No invertible con Jacobi')
        
        residuo = np.linalg.norm( b - np.dot(A,x) )
        
    return it



In [10]:
it = GetacobiMethod(M,b)
it

26

# Gauss-seidel

In [11]:
x = 0
y = 0
z = 0
error = 1e-10
it = 0
while True:
    a = x
    x = (1 + y + z)/3
    y = (3+x-z)/3
    z = (7-2*x-y)/4
    e = abs((x-a)/x)
        
    if e<error:
        break
    it +=1
    
it
        
    
    

17