In [1]:
import numpy as np

In [2]:
A = np.array([[1,0,0],[5,1,0],[-2,3,1]])
A

array([[ 1,  0,  0],
       [ 5,  1,  0],
       [-2,  3,  1]])

In [3]:
B = np.array([[4,-2,1],[0,3,7],[0,0,2]])
B

array([[ 4, -2,  1],
       [ 0,  3,  7],
       [ 0,  0,  2]])

In [15]:
e = np.array([])
for i in A:
    for j in range(3):
        r = sum(i*B[:,j])
        e = np.append(e,r)
e

array([ 4., -2.,  1., 20., -7., 12., -8., 13., 21.])

In [20]:
m = np.array([e[:3],e[3:6],e[6:]])
m


array([[ 4., -2.,  1.],
       [20., -7., 12.],
       [-8., 13., 21.]])