In [2]:
import numpy as np
import sympy as sym

In [3]:
b=np.array([[-3],[-3],[8],[9]])
b

array([[-3],
       [-3],
       [ 8],
       [ 9]])

In [16]:
u1=np.array([3,1,0,1])
u2=np.array([1,2,2,1])
u3=np.array([-1,0,2,-1])
u1,u2,u3

(array([3, 1, 0, 1]), array([1, 2, 2, 1]), array([-1,  0,  2, -1]))

# Punto a.

In [73]:
A=np.array([u1,u2,u3]).T
A     

array([[ 3,  1, -1],
       [ 1,  2,  0],
       [ 0,  2,  2],
       [ 1,  1, -1]])

In [74]:
A.T

array([[ 3,  1,  0,  1],
       [ 1,  2,  2,  1],
       [-1,  0,  2, -1]])

In [75]:
AAT=np.dot(A.T,A)
AAT

array([[11,  6, -4],
       [ 6, 10,  2],
       [-4,  2,  6]])

In [76]:
ATb=np.dot(A.T,b)
ATb

array([[-3],
       [16],
       [10]])

In [77]:
x=np.linalg.solve(AAT,ATb)
x

array([[-2.44444444],
       [ 3.27777778],
       [-1.05555556]])

In [78]:
def proy_ort(A,x):
    p = np.dot(A,x)
    return p

In [79]:
proy_ort(A,x)

array([[-3.        ],
       [ 4.11111111],
       [ 4.44444444],
       [ 1.88888889]])

# Punto b.

In [5]:
mag_u1=np.linalg.norm(u1)
v1=u1*(1/(mag_u1))
v1

array([0.90453403, 0.30151134, 0.        , 0.30151134])

In [6]:
def gram_schmidt(v1,u2,u3):
    u2p = u2-(np.dot(u2,v1))*v1
    v2 = u2p*(1/np.linalg.norm(u2p))
    u3p = (u3-(np.dot(u3,v1)*v1)) - (np.dot(u3,v2))*v2
    v3= u3p*(1/np.linalg.norm(u3p))
    base=(v1,v2,v3)
    return base
    

In [8]:
v = gram_schmidt(v1,u2,u3)
v[0]

array([0.90453403, 0.30151134, 0.        , 0.30151134])

In [10]:
b = np.array([-3, -3,  8,  9])
c = np.zeros(3)
for i in range(3):
    c[i]=np.dot(b,v[i])
c

array([-0.90453403,  6.79969648, -1.47247009])

In [15]:
for i in range(3):
    p = (c[i]*v[i])
    print(p)

[-0.81818182 -0.27272727 -0.         -0.27272727]
[-1.66830467  3.81326781  5.24324324  1.19164619]
[-0.51351351  0.57057057 -0.7987988   0.96996997]


In [207]:
-0.81818182-1.66830467-0.51351351

-3.0

In [188]:
-0.27272727+3.81326781+0.57057057

4.11111111

In [14]:
0.+5.24324324-0.7987988

4.44444444

In [190]:
-0.27272727+1.19164619+0.96996997

1.8888888899999998

In [17]:
for i in range(4):
    pwb = c[i]+v[i]
    print(pwb)

[ 1.11022302e-16 -6.03022689e-01 -9.04534034e-01 -6.03022689e-01]
[6.55434661 7.36049619 7.57079608 6.97494639]
[-1.12372717 -1.85996222 -0.92998111 -2.13120671]


IndexError: index 3 is out of bounds for axis 0 with size 3